# Docker and testing
version: "3"

services:
  back-end:
    build: ./back-end
    container_name: back-end
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
  front-end:
    build: ./front-end
    container_name: front-end
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - back-end
  mongo:
    image: mongo:4.2.3-bionic
    restart: unless-stopped
    ports:
      - "27017:27017"
